// Code generated by git.sr.ht/~sircmpwn/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Upc   string `json:"upc"`
	Name  string `json:"name"`
	Price int    `json:"price"`
}

func (Product) IsEntity() {}
