// Code generated by git.sr.ht/~sircmpwn/gqlgen, DO NOT EDIT.

package model

import (
	"git.sr.ht/~sircmpwn/gqlgen/example/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
